# -*- coding: utf-8 -*-
"""aula1GitHub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VDmmt5kD9ghzRouHZsmPKJbmZD6hdaKm
"""



print ('Meu primeiro artefato no GitHub!')