# -*- coding: utf-8 -*-
"""DesafioEstruturaSequencial

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lvJUXGHYsCLcz5__RYXBMc3h1XIndxT0

1.Faça um Programa que mostre a mensagem "Alô ETE PORTO DIGITAL!" na tela via

Colab ou Repl.it
"""

print("Alô ETE PORTO DIGITAL!")

"""2.Faça um Programa que peça um número e então mostre a mensagem 'O número informado foi [número]'."""

numero = int(input("Informe um número: "))
print("O número informado foi %i " %numero)

"""3.Faça um Programa que peça dois números e imprima a soma."""

numero1 = int(input("Informe um número: "))
numero2 = int(input("Informe um número: "))
print("A soma é %i"  %(numero1+numero2))

"""4.Faça um Programa que peça as 4 notas bimestrais e mostre a média"""

soma = 0
for i in range(4):
  numero = int(input("Nota %i: " %(i+1)))
  soma+=numero
media = soma/4
print("A media é %.1f" %media)

"""5.Faça um Programa que converta metros para centímetros."""

centimetros = float(input("Informe o comprimento em centimetros (cm): "))

metros = centimetros/100

print("%.2f cm em metro é %.2f m"%(centimetros, metros))

"""6.Faça um Programa que peça o raio de um círculo, calcule e mostre sua área."""

raio = int(input("Informe o raio em (cm): "))
area_circ = 2*raio**2

print("A area da circunferencia de raio %i cm é %.2f cm²" %(raio, area_circ))

"""7.Faça um Programa que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário."""

lado = int(input("Informe o lado em (cm): "))
area_quad = lado**2

print("O dobro da area é %i cm²"%(2*area_quad))

"""8.Faça um Programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês."""

hora = int(input("horas trabalhadas por mes: "))
valor = float(input("Valor da hora: "))

total = hora*valor

print("O salário vai ser de %.2f" %total)

"""9.Faça um Programa que peça a temperatura em graus Fahrenheit, transforme e mostre a temperatura em graus Celsius. C = 5 * ((F-32) / 9)."""

F = float(input("informe a temperatura em Fareneit: "))
C = 5 * ((F-32) / 9)

print("A temperatura de %.2f °F em Celsius é de %.2f °C"%(F,C))

"""10.Faça um Programa que peça a temperatura em graus Celsius, transforme e mostre em graus Fahrenheit."""

C = float(input("informe a temperatura em Celsius: "))
F = (9*C - 32)/5

print("A temperatura de %.2f °C em Fahrenheit é de %.2f °F"%(C,F))

"""11.Faça um Programa que peça 2 números inteiros e um número real. Calcule e mostre: o produto do dobro do primeiro com metade do segundo. a soma do triplo do primeiro com o terceiro. O terceiro elevado ao cubo."""

numero1 = int(input("Informe um número inteiro: "))
numero2 = int(input("Informe um número inteiro: "))
numero3 = float(input("Informe um número real: "))

calculo1 = 2*numero1 + numero2/2
calculo2 = 3*numero1 + numero3
calculo3 = numero3**3

print("2*%i + %i/2 = %.2f" %(numero1,numero2,calculo1))
print("3*%i + %.2f = %.2f" %(numero1,numero3,calculo2))
print("%i³ = %.2f" %(numero3,calculo3))

"""12.Tendo como dados de entrada a altura de uma pessoa, construa um algoritmo que calcule seu peso ideal, usando a seguinte fórmula: (72.7*altura) - 58"""

altura = float(input("Informe a altura em (m): "))
PesoIdeal = (72.7*altura) - 58
print("O peso ideal para a altura %.2f é de %.2f" %(altura,PesoIdeal))

"""13.Tendo como dado de entrada a altura (h) de uma pessoa, construa um algoritmo que calcule seu peso ideal, utilizando as seguintes fórmulas: Para homens: (72.7*h) - 58.  Para mulheres: (62.1*h) - 44.7"""

altura = float(input("Informe a altura em (m): "))
Peso_Ideal_homens = (72.7*altura) - 58
Peso_Ideal_mulher = (62.1*altura) - 44.7
print("O peso ideal do homem para a altura %.2f é de %.2f" %(altura,Peso_Ideal_homens))
print("O peso ideal da mulher para a altura %.2f é de %.2f" %(altura,Peso_Ideal_mulher))

"""14.João Papo-de-Pescador, homem de bem, comprou um microcomputador para controlar o rendimento diário de seu trabalho. Toda vez que ele traz um peso de peixes maior que o estabelecido pelo regulamento de pesca do estado de São Paulo (50 quilos) deve pagar uma multa de R$ 4,00 por quilo excedente. João precisa que você faça um programa que leia a variável peso (peso de peixes) e calcule o excesso. Gravar na variável excesso a quantidade de quilos além do limite e na variável multa o valor da multa que João deverá pagar. Imprima os dados do programa com as mensagens adequadas."""

PesoPeixe = float(input("Peso do peixe (Kg): "))

if PesoPeixe > 50:
  multa = (PesoPeixe - 50)*4  

print("A multa a ser paga por Kg excedente é de %.2f" %multa)

"""15.Faça um programa que peça o tamanho de um arquivo para download (em MB) e a velocidade de um link de Internet (em Mbps), calcule e informe o tempo aproximado de download do arquivo usando este link (em minutos)."""

MB = int(input("Informe o tamanho do arquivo (MB): "))

Velocidade =  128.31 # Verificado no SpeedTest em (Mbps)

Tempo_Download = (MB/Velocidade)/60

print("O tempo para download do arquivo de tamanho %.2f MB é de aproximadamente %.0f minutos" %(MB, Tempo_Download))