# -*- coding: utf-8 -*-
"""DesafioEstruturaRepeticao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oC8HaxqIZQmRdVaEFa5ex_I5kDqumnMa

ETE PORTO DIGITAL

DISCIPLINA: LPC - 2022

PROFESSOR: Cloves Rocha

ALUNA: Joyce Costa

1.Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
"""

confere = True
while confere:
  nota = float(input("Informe uma nota entre 0 e 10: "))
  if nota >= 0 and nota <= 10:
    confere = False
  else:
    print("\nNota inválida!\n")

"""2.Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações."""

confere = True
while confere:
  login = input("Login: ")
  senha = input("Senha: ")
   
  if login != senha:
    confere = False 
  else:
    print("\nLogin e senha iguais! Informe diferente\n")

"""3.Supondo que a população de um país A seja da ordem de 80000 habitantes com uma taxa anual de crescimento de 3% e que a população de B seja 200000 habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e escreva o número de anos necessários para que a população do país A ultrapasse ou iguale a população do país B, mantidas as taxas de crescimento."""

cidadeA = 80000
cidadeB = 200000

cont = 0
while cidadeA < cidadeB:

  cidadeA+=cidadeA*0.03
  cidadeB+=cidadeB*0.015

  cont+=1

print("A cidade A ultrapassa a cidade B em %i anos" %cont)
print("A cidade A com %.2f e a cidade B com %.2f" %(cidadeA,cidadeB))

"""4.Altere o programa anterior permitindo ao usuário informar as populações e as taxas de crescimento iniciais. Valide a entrada e permita repetir a operação.

"""

cidadeA = float(input("Informe a população da cidade A: "))
Taxa_A = float(input("Informe a taxa de crescimento da cidade A: "))
cidadeB = float(input("Informe a população da cidade B: "))
Taxa_B = float(input("Informe a taxa de crescimento da cidade B: "))


cont = 0
while cidadeA < cidadeB:

  cidadeA+=cidadeA*Taxa_A
  cidadeB+=cidadeB*Taxa_B

  cont+=1

print("\n\nA cidade A ultrapassa a cidade B em %i anos" %cont)
print("A cidade A com %.2f e a cidade B com %.2f" %(cidadeA,cidadeB))

"""5.Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro.

"""

for i in range(20):
  print(i+1)

print("\n\n")
for i in range(20):
  print(i+1, end=" ")

"""6.Faça um programa que leia 5 números e informe o maior número."""

lista = []
for i in range(5):
  num = int(input("Número: "))
  lista.append(num)

print("O maior número é o", max(lista))

"""7.Faça um programa que leia 5 números e informe a soma e a média dos números."""

lista = []
soma = 0
for i in range(5):
  num = int(input("Número: "))
  soma += num

media = soma/5
print("A soma é ", soma)

print("A média é %.2f" %media)

"""8.Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50.

"""

for i in range(50):
  
  if (i+1)%2 != 0:
    print(i+1, end=' ')

"""9.Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles.

"""

num1 = float(input("Informe o inicio: "))
num2 = float(input("Informe o final: "))
for i in range(int(num1), int(num2)):
    print(i+1, end=' ')

"""10.Altere o programa anterior para mostrar no final a soma dos números.

"""

num1 = float(input("Informe o inicio: "))
num2 = float(input("Informe o final: "))
soma = 0
for i in range(int(num1), int(num2)):
  soma += i
print("A soma é %i"%soma)

"""11.Faça um programa que calcule o valor total investido por um colecionador em sua coleção de CDs e o valor médio gasto em cada um deles. O usuário deverá informar a quantidade de CDs e o valor para em cada um.

"""

cd = int(input("Qual sua quantidade de CD:"))
soma = 0
for i in range(cd):
  valorCD = float(input("Qual o valor: "))
  soma+=valorCD

media = soma/cd

print("O total gasto nos CD's foi de %.2f" %soma)
print("A média gasto por CD's foi de %.2f" %media)

"""12.Faça um programa que leia dez conjuntos de dois valores, o primeiro representando o número do aluno e o segundo representando a sua altura em centímetros. Encontre o aluno mais alto e o mais baixo. Mostre o número do aluno mais alto e o número do aluno mais baixo, junto com suas alturas.

"""

#Alunos_Alturas = [[1,1.64],[2,1.78],[3,1.56],[4,2.00],[5,1.45],[6,1.43],[7,1.41],[8,1.40],[9,1.42],[10,1.39]]
Alunos_Alturas = []
for aux in range(10):
  Altura = float(input("Altura do aluno %i: " %(aux+1)))
  Alunos_Alturas.append([(aux+1),Altura])
maior = Alunos_Alturas[0][1]  
for j in range(1,len(Alunos_Alturas)):
  if(maior < Alunos_Alturas[j][1]):
    maior = Alunos_Alturas[j][1]
    numero_Aluno = Alunos_Alturas[j][0]
     
print("O aluno mais alto é o %i com altura de %.2f" %(numero_Aluno,maior))

"""13.Faça um programa que leia uma quantidade indeterminada de números positivos e conte quantos deles estão nos seguintes intervalos: [0-25], [26-50], [51-75] e [76-100]. A entrada de dados deverá terminar quando for lido um número negativo.

"""

confere = True
cont1=0
cont2=0
cont3=0
cont4=0
while confere:
  num = float(input("Número: "))

  if num>=0 and num<=25:
    cont1+=1
  elif num>=26 and num<=50:
    cont2+=1
  elif num>=51 and num<=75:
    cont3+=1
  elif num>=76 and num<=100:
    cont4+=1
  elif num<0:
    confere = False
print("[0   |  25]: %i" %cont1)
print("[26  |  50]: %i" %cont2)
print("[51  |  75]: %i" %cont3)
print("[76  | 100]: %i" %cont4)

"""14.Faça um programa que mostre os n termos da Série a seguir:
  S = 1/1 + 2/3 + 3/5 + 4/7 + 5/9 + ... + n/m. Imprima no final a soma da série.
"""

termos = int(input("Informe a qunatidade de termos: "))

soma = 0
m=-1
for n in range(termos):
  m += 2
  soma += (n+1)/(m)
print("A soma foi de %.4f" %soma)