# -*- coding: utf-8 -*-
"""DesafioEstruturaDecisao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nmUf1PHRzlI0xoh3WGhGrE0lF3zpgnKR

# ETE PORTO DIGITAL
# DISCIPLINA: LPC - 2022
# PROFESSOR: Cloves Rocha
# ALUNA: Joyce Costa

1.Faça um Programa que peça dois números e imprima o maior deles.
"""

num1 = int(input("Informe um número: "))
num2 = int(input("Informe um número: "))

if num1 > num2:
  print("O maior é %i" %num1)

else:
  print("O maior é %i" %num2)

"""2.Faça um Programa que peça um valor e mostre na tela se o valor é positivo ou negativo."""

num = int(input("Número: "))

if num > 0:
  print("Número POSITIVO")

else:
  print("Número NEGATIVO")

"""3.Faça um Programa que verifique se uma letra digitada é "F" ou "M". Conforme a letra escrever: F - Feminino, M - Masculino, Sexo Inválido."""

sexo = input("[F|M]: ").lower()

if sexo=="f":
  print("Feminino")

elif sexo=="m":
  print("Masculino")

else:
  print("Sexo inválido!")

"""Faça um Programa que verifique se uma letra digitada é vogal ou consoante"""

letra = input("Letra: ").lower()
if letra in ['a','e','i','o','u']:
  print("Vogal!")

else:
  print("Consoante!")

"""5.Faça um Programa que leia três números e mostre o maior deles.

"""

lista = []
for i in range(3):
  num = int(input("Informe um número: "))
  lista.append(num)

print("O maior é %i " %max(lista))

"""6.Faça um Programa que leia três números e mostre o maior e o menor deles."""

lista = []
for i in range(3):
  num = int(input("Informe um número: "))
  lista.append(num)

print("O maior é %i " %max(lista))
print("O menor é %i " %min(lista))

"""7. Faça um programa que pergunte o preço de três produtos e informe qual produto você deve comprar, sabendo que a decisão é sempre pelo mais barato."""

lista = []
for i in range(3):
  valor = float(input("Informe o valor do produto: "))
  lista.append(valor)

print("O mais barato é %.2f " %min(lista))

"""8.Faça um Programa que leia três números e mostre-os em ordem decrescente."""

lista = []
for i in range(3):
  num = int(input("Informe número: "))
  lista.append(num)
print("Lista: ", lista)
lista.reverse() # Não retorna uma cópia, altera a lista original
print("Lista invertida: ", lista)

"""9.Faça um Programa que pergunte em que turno você estuda. Peça para digitar M-matutino ou V-Vespertino ou N- Noturno. Imprima a mensagem "Bom Dia!", "Boa Tarde!" ou "Boa Noite!" ou "Valor Inválido!", conforme o caso."""

print("M - Matutino\nV - Vesperino\nN - Noturno")
turno = input("Qual turno: ").upper()

if turno == 'M':
  print("Bom dia!")

elif turno == 'V':
  print("Boa tarde!")

elif turno == 'N':
  print("Boa noite!")

else:
  print("Opção Inválida!")

"""10.Faça um Programa que peça um número correspondente a um determinado ano e em seguida informe se este ano é ou não bissexto."""

ano = int(input("Informe o ano: "))

if ano%4 ==0:
  print("Esse ano é bissexto")

else:
  print("Não é bissexto!")

"""11.Faça um Programa que peça uma data no formato dd/mm/aaaa e determine se a mesma é uma data válida."""

data = input("Informe a data no modelo[dd/mm/aaaa]: ")


if data[2] == "/" and data[5] == "/":
  #print("barras no local certo")

  lista_data = data.split('/') #Separa a String pelo metodo que quiser
  if int(lista_data[0]) > 0 and int(lista_data[0]) < 31:
    #print("dia certo")  

    if int(lista_data[1]) > 0 and int(lista_data[1]) <= 12:
      #print("mes certo")
    
      if int(lista_data[2]) > 0:
        print("\nO formato da data está correta: %s" %data)
      else:
        print("\nFormato da data incorreto")

  else:
    print("\nFormato da data incorreto")

else:
  print("\nFormato da data incorreto")

"""12.Faça um programa que faça 5 perguntas para uma pessoa sobre um crime. As perguntas são:
a. "Telefonou para a vítima?"
b. "Esteve no local do crime?"
c. "Mora perto da vítima?"
d. "Devia para a vítima?"
e. "Já trabalhou com a vítima?" O programa deve no final emitir uma classificação sobre a participação da pessoa no crime. Se a pessoa responder positivamente a 2 questões ela deve ser classificada como "Suspeita", entre 3 e 4 como "Cúmplice" e 5 como "Assassino". Caso contrário, ele será classificado como "Inocente".
"""

perguntas = ["a. Telefonou para a vítima? ","b. Esteve no local do crime? ", "c. Mora perto da vítima? ", "d. Devia para a vítima? ", "e. Já trabalhou com a vítima? "]
cont = 0

for perguntando in perguntas:
  resposta = input(perguntando+'[S|N]: ').lower()
  if resposta == 's':
    cont+=1

if cont == 2:
  print("\nSusteito")

elif cont == 3 or cont == 4:
  print("\nCúmplice")

elif cont == 5:
  print("\nAssassino!")

else:
  print("\nsInocente")